spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  mail:
    transport:
      protocol:
        smtp
    host:
      smtp.exmail.qq.com
    username:
      xxxxxxxxxxx
    password:
      xxxxxxxxxxx
    properties:
      mail:
        smtp:
          socketFactory:
            port:
              465
          auth:
            true
debug: true

file:
  output:
    path: /Users/shuai/Documents/backup/gongzi/